<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="40519" started-at="2014-09-04T11:02:16Z" finished-at="2014-09-04T11:02:57Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="40519" started-at="2014-09-04T11:02:16Z" finished-at="2014-09-04T11:02:57Z">
      <class name="raghu.sample_trail">
        <test-method status="FAIL" signature="test()[pri:0, instance:raghu.sample_trail@2df5ccb3]" name="test" duration-ms="40485" started-at="2014-09-04T16:32:16Z" finished-at="2014-09-04T16:32:57Z">
          <exception class="java.lang.RuntimeException">
            <message>
              <![CDATA[Exception caught while executing verifyElementFound: Element xpath=//*[@text='examplpalya@gmail.com'] wasn't found]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.RuntimeException: Exception caught while executing verifyElementFound: Element xpath=//*[@text='examplpalya@gmail.com'] wasn't found
	at com.experitest.client.Client.execute(Client.java:161)
	at com.experitest.client.Client.verifyElementFound(Client.java:1649)
	at raghu.sample_trail.test(sample_trail.java:42)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(Unknown Source)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(Unknown Source)
	at java.lang.reflect.Method.invoke(Unknown Source)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:84)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:714)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:901)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1231)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:127)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:111)
	at org.testng.TestRunner.privateRun(TestRunner.java:767)
	at org.testng.TestRunner.run(TestRunner.java:617)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:334)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:329)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:291)
	at org.testng.SuiteRunner.run(SuiteRunner.java:240)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1224)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1149)
	at org.testng.TestNG.run(TestNG.java:1057)
	at org.testng.remote.RemoteTestNG.run(RemoteTestNG.java:111)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:204)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:175)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.RuntimeException -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- test -->
      </class> <!-- raghu.sample_trail -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
